// Crystal Light Theme Colors
export const crystalLightColors = {
  focusBorder: "#4078f2",
  foreground: "#383a42",
  descriptionForeground: "#939496",
  errorForeground: "#ff0000",

  "textLink.foreground": "#4078f2",
  "textLink.activeForeground": "#1e64fa",
  "textBlockQuote.background": "#f9f9f9",
  "textBlockQuote.border": "#383a4228",
  "textCodeBlock.background": "#f2f2f2",
  "textPreformat.foreground": "#a0a1a7",
  "textPreformat.background": "#f9f9f9",
  "textSeparator.foreground": "#383a4228",

  "icon.foreground": "#383a42",
  "keybindingLabel.foreground": "#383a42",

  "button.background": "#4078f2",
  "button.foreground": "#ffffff",
  "button.hoverBackground": "#4078f2e3",

  "button.secondaryBackground": "#f2f2f2",
  "button.secondaryForeground": "#383a42",
  "button.secondaryHoverBackground": "#e9e9e9",

  "checkbox.background": "#f2f2f2",
  "checkbox.border": "#383a4228",

  "dropdown.background": "#f2f2f2",
  "dropdown.border": "#383a4228",
  "dropdown.foreground": "#383a42",
  "dropdown.listBackground": "#f9f9f9",

  "input.background": "#f2f2f2",
  "input.border": "#383a4228",
  "input.foreground": "#383a42",
  "input.placeholderForeground": "#383a4280",

  "badge.foreground": "#ffffff",
  "badge.background": "#4078f2",

  "progressBar.background": "#4078f2",

  "titleBar.activeForeground": "#383a42",
  "titleBar.activeBackground": "#f9f9f9",
  "titleBar.inactiveForeground": "#383a42",
  "titleBar.inactiveBackground": "#f9f9f9",
  "titleBar.border": "#383a4228",

  "activityBar.foreground": "#383a42",
  "activityBar.inactiveForeground": "#383a42C5",
  "activityBar.background": "#f9f9f9",
  "activityBarBadge.foreground": "#ffffff",
  "activityBarBadge.background": "#4078f2",
  "activityBar.activeBorder": "#4078f2",
  "activityBar.border": "#383a4228",

  "sideBar.foreground": "#383a42",
  "sideBar.background": "#f9f9f9",
  "sideBar.border": "#383a4228",
  "sideBarTitle.foreground": "#383a42",
  "sideBarSectionHeader.foreground": "#383a42",
  "sideBarSectionHeader.background": "#f9f9f9",
  "sideBarSectionHeader.border": "#383a4228",

  "list.hoverForeground": "#383a42",
  "list.inactiveSelectionForeground": "#383a42",
  "list.activeSelectionForeground": "#383a42",
  "list.hoverBackground": "#e9e9e9",
  "list.inactiveSelectionBackground": "#e9e9e9",
  "list.activeSelectionBackground": "#e9e9e9",
  "list.inactiveFocusBackground": "#e9e9e9",
  "list.focusForeground": "#383a42",
  "list.focusBackground": "#d3d4d6",
  "list.highlightForeground": "#4078f2",

  "tree.indentGuidesStroke": "#a0a1a770",

  "notificationCenterHeader.foreground": "#383a42",
  "notificationCenterHeader.background": "#e1e1e1",
  "notifications.foreground": "#383a42",
  "notifications.background": "#f9f9f9",
  "notifications.border": "#383a4245",
  "notificationsErrorIcon.foreground": "#ff0000",
  "notificationsWarningIcon.foreground": "#e9a700",
  "notificationsInfoIcon.foreground": "#4078f2",

  "pickerGroup.border": "#383a4228",
  "pickerGroup.foreground": "#4078f2",
  "quickInput.background": "#f9f9f9",
  "quickInput.foreground": "#383a42",

  "statusBar.foreground": "#383a42",
  "statusBar.background": "#f9f9f9",
  "statusBar.border": "#383a4228",
  "statusBar.focusBorder": "#4078f2",
  "statusBar.noFolderBackground": "#f9f9f9",
  "statusBar.debuggingForeground": "#ffffff",
  "statusBar.debuggingBackground": "#4078f2",
  "statusBarItem.prominentBackground": "#e9e9e9",
  "statusBarItem.remoteForeground": "#383a42",
  "statusBarItem.remoteBackground": "#f9f9f9",
  "statusBarItem.hoverBackground": "#D3D4D6",
  "statusBarItem.activeBackground": "#c3c4c6",
  "statusBar.noFolderForeground": "#383a42",

  "editorGroupHeader.tabsBackground": "#f9f9f9",
  "editorGroupHeader.tabsBorder": "#383a4228",
  "editorGroup.border": "#383a4228",

  "tab.activeForeground": "#383a42",
  "tab.inactiveForeground": "#a0a1a7",
  "tab.inactiveBackground": "#f9f9f9",
  "tab.activeBackground": "#f9f9f9",
  "tab.hoverBackground": "#eeeeef",
  "tab.unfocusedHoverBackground": "#eeeeef",
  "tab.border": "#383a4228",
  "tab.unfocusedActiveBorderTop": "#383a4228",
  "tab.activeBorder": "#f9f9f9",
  "tab.unfocusedActiveBorder": "#f9f9f9",
  "tab.activeBorderTop": "#4078f2",

  "breadcrumb.foreground": "#a0a1a7",
  "breadcrumb.focusForeground": "#383a42",
  "breadcrumb.activeSelectionForeground": "#383a42",
  "breadcrumbPicker.background": "#f9f9f9",

  "editor.foreground": "#383a42",
  "editor.background": "#f9f9f9",
  "editorWidget.background": "#f9f9f9",
  "editor.foldBackground": "#edededf9",
  "editor.lineHighlightBackground": "#ededed",
  "editor.lineHighlightBorder": "#29416100",
  "editorLineNumber.foreground": "#a0a1a7",
  "editorLineNumber.activeForeground": "#383a42",
  "editorIndentGuide.background": "#a0a1a730",
  "editorIndentGuide.activeBackground": "#a0a1a790",
  "editorWhitespace.foreground": "#a0a1a770",
  "editorCursor.foreground": "#383a42",

  "editor.findMatchBackground": "#FFA657",
  "editor.findMatchHighlightBackground": "#f0c5abf9",
  "editor.linkedEditingBackground": "#cedcff",
  "editor.inactiveSelectionBackground": "#e3ebfffa",
  "editor.selectionBackground": "#cedcff",
  "editor.selectionHighlightBackground": "#d0d0d070",
  "editor.selectionHighlightBorder": "#383a4215",
  "editor.wordHighlightBackground": "#d0d0d070",
  "editor.wordHighlightStrongBackground": "#61AFEF35",
  "editor.wordHighlightBorder": "#383a4215",
  "editor.wordHighlightStrongBorder": "#383a4215",
  "editorBracketMatch.background": "#d0d0d070",
  "editorBracketMatch.border": "#383a4225",

  "editorInlayHint.background": "#f9f9f9",
  "editorInlayHint.foreground": "#a0a1a7",
  "editorInlayHint.typeBackground": "#f9f9f9",
  "editorInlayHint.typeForeground": "#a0a1a7",
  "editorInlayHint.paramBackground": "#f9f9f9",
  "editorInlayHint.paramForeground": "#a0a1a7",

  "editorGutter.modifiedBackground": "#4078f2",
  "editorGutter.addedBackground": "#50A14F",
  "editorGutter.deletedBackground": "#E45649",

  "diffEditor.insertedLineBackground": "#e3ebfffa",
  "diffEditor.insertedTextBackground": "#cedcff",
  "diffEditor.removedLineBackground": "#f0c5abf9",
  "diffEditor.removedTextBackground": "#f9ba8275",

  "scrollbar.shadow": "#00000020",
  "scrollbarSlider.background": "#a3a4a6a9",
  "scrollbarSlider.hoverBackground": "#a3a4a6b5",
  "scrollbarSlider.activeBackground": "#a3a4a6d5",
  "editorOverviewRuler.border": "#383a4228",

  "minimapSlider.background": "#a3a4a6a9",
  "minimapSlider.hoverBackground": "#a3a4a6b5",
  "minimapSlider.activeBackground": "#a3a4a6d5",

  "panel.background": "#f9f9f9",
  "panel.border": "#383a4228",
  "panelTitle.activeBorder": "#4078f2",
  "panelTitle.activeForeground": "#383a42",
  "panelTitle.inactiveForeground": "#a0a1a7",
  "panelInput.border": "#383a4228",

  "debugIcon.breakpointForeground": "#ff0000",
  "debugConsole.infoForeground": "#4078f2",
  "debugConsole.warningForeground": "#e9a700",
  "debugConsole.errorForeground": "#ff0000",
  "debugConsole.sourceForeground": "#383a42",
  "debugConsoleInputIcon.foreground": "#4078f2",

  "debugTokenExpression.name": "#4078f2",
  "debugTokenExpression.value": "#383a42",
  "debugTokenExpression.string": "#A626A4",
  "debugTokenExpression.boolean": "#50A14F",
  "debugTokenExpression.number": "#986801",
  "debugTokenExpression.error": "#ff0000",

  "symbolIcon.arrayForeground": "#986801",
  "symbolIcon.booleanForeground": "#50A14F",
  "symbolIcon.classForeground": "#A626A4",
  "symbolIcon.colorForeground": "#4078f2",
  "symbolIcon.constructorForeground": "#A626A4",
  "symbolIcon.enumeratorForeground": "#986801",
  "symbolIcon.enumeratorMemberForeground": "#986801",
  "symbolIcon.eventForeground": "#a0a1a7",
  "symbolIcon.fieldForeground": "#a0a1a7",
  "symbolIcon.fileForeground": "#383a42",
  "symbolIcon.folderForeground": "#383a42",
  "symbolIcon.functionForeground": "#4078f2",
  "symbolIcon.interfaceForeground": "#A626A4",
  "symbolIcon.keyForeground": "#4078f2",
  "symbolIcon.keywordForeground": "#A626A4",
  "symbolIcon.methodForeground": "#4078f2",
  "symbolIcon.moduleForeground": "#A626A4",
  "symbolIcon.namespaceForeground": "#A626A4",
  "symbolIcon.nullForeground": "#a0a1a7",
  "symbolIcon.numberForeground": "#986801",
  "symbolIcon.objectForeground": "#383a42",
  "symbolIcon.operatorForeground": "#4078f2",
  "symbolIcon.packageForeground": "#383a42",
  "symbolIcon.propertyForeground": "#383a42",
  "symbolIcon.referenceForeground": "#4078f2",
  "symbolIcon.snippetForeground": "#4078f2",
  "symbolIcon.stringForeground": "#50A14F",
  "symbolIcon.structForeground": "#A626A4",
  "symbolIcon.textForeground": "#383a42",
  "symbolIcon.typeParameterForeground": "#A626A4",
  "symbolIcon.unitForeground": "#986801",
  "symbolIcon.variableForeground": "#383a42",
  "symbolIcon.constantForeground": "#ff0000",

  "terminal.ansiBlack": "#383a42",
  "terminal.ansiRed": "#ff0000",
  "terminal.ansiGreen": "#50A14F",
  "terminal.ansiYellow": "#986801",
  "terminal.ansiBlue": "#1890f3",
  "terminal.ansiMagenta": "#A626A4",
  "terminal.ansiCyan": "#61AFEF",
  "terminal.ansiWhite": "#a0a1a7",
  "terminal.ansiBrightBlack": "#a0a1a7",
  "terminal.ansiBrightRed": "#ff0000",
  "terminal.ansiBrightGreen": "#50A14F",
  "terminal.ansiBrightYellow": "#fd9132",
  "terminal.ansiBrightBlue": "#005fb8",
  "terminal.ansiBrightMagenta": "#A626A4",
  "terminal.ansiBrightCyan": "#4078f2",
  "terminal.ansiBrightWhite": "#ffffff",

  "editorBracketHighlight.foreground1": "#E45649",
  "editorBracketHighlight.foreground2": "#4078F2",
  "editorBracketHighlight.foreground3": "#A626A4",
  "editorBracketHighlight.foreground4": "#50A14F",
  "editorBracketHighlight.foreground5": "#986801",
  "editorBracketHighlight.foreground6": "#005CC5",
  "editorBracketHighlight.unexpectedBracket.foreground": "#a0a1a7",

  "gitDecoration.addedResourceForeground": "#50A14F",
  "gitDecoration.modifiedResourceForeground": "#4078F2",
  "gitDecoration.deletedResourceForeground": "#E45649",
  "gitDecoration.untrackedResourceForeground": "#50A14F",
  "gitDecoration.ignoredResourceForeground": "#a0a1a7",
  "gitDecoration.conflictingResourceForeground": "#ff0000",
  "gitDecoration.submoduleResourceForeground": "#a0a1a7",

  "debugToolBar.background": "#f9f9f9",
  "editor.stackFrameHighlightBackground": "#ffd33d33",
  "editor.focusedStackFrameHighlightBackground": "#50A14F33",

  "peekViewEditor.matchHighlightBackground": "#f0c5abf9",
  "peekViewResult.matchHighlightBackground": "#f0c5abf9",
  "peekViewEditor.background": "#f2f8fc",
  "peekViewResult.background": "#f9f9f9",

  "settings.headerForeground": "#2f363d",
  "settings.modifiedItemIndicator": "#4078f2",
  "welcomePage.buttonBackground": "#f2f2f2",
  "welcomePage.buttonHoverBackground": "#e9e9e9",

  "commandCenter.foreground": "#383a42",
  "commandCenter.background": "#f2f2f2",
  "commandCenter.border": "#383a4228",
  "commandCenter.activeBackground": "#e3e4e6D5",
  "commandCenter.activeForeground": "#383a42",
  "commandCenter.activeBorder": "#383a4228",
  "toolbar.hoverBackground": "#b3b4b650",
  "toolbar.activeBackground": "#b3b4b660",
  "menubar.selectionForeground": "#383a42",
  "menubar.selectionBackground": "#b3b4b650",
  "menubar.selectionBorder": "#00000000",
  "menu.background": "#f9f9f9",
  "menu.foreground": "#383a42",
  "menu.selectionForeground": "#383a42",
  "menu.selectionBackground": "#e3e4e6",
  "menu.selectionBorder": "#00000000",
  "menu.separatorBackground": "#383a4228",
  "menu.border": "#383a4228",
  "activityBar.activeBackground": "#00000000",
  "sideBar.dropBackground": "#4078f295",
  "listFilterWidget.background": "#f9f9f9",
  "listFilterWidget.outline": "#383a4228",
  "list.dropBackground": "#8fb0f7",
  "statusBar.debuggingBorder": "#383a4228",
  "statusBar.noFolderBorder": "#383a4228",
  "statusBarItem.hoverForeground": "#383a42",
  "editorGroup.dropBackground": "#4078f295",
  "tab.hoverForeground": "#383a42",
  "breadcrumb.background": "#f9f9f9",
  "editorWidget.border": "#383a4228",
  "editorWidget.foreground": "#383a42",
  "editorWidget.resizeBorder": "#4078f2",
  "editorIndentGuide.background1": "#a0a1a730",
  "editorIndentGuide.activeBackground1": "#a0a1a790",
  "editorGutter.foldingControlForeground": "#a0a1a7",
  "editorCodeLens.foreground": "#a0a1a7",
  "editorOverviewRuler.background": "#fd0a0a00",
  "editor.selectionForeground": "#383a42",
  "editorWatermark.foreground": "#383a42",
  "editorStickyScroll.background": "#f9f9f9",
  "editorStickyScrollHover.background": "#ededed",
  "minimap.background": "#f9f9f9",
  "minimap.selectionHighlight": "#4078f2f9",
  "minimap.findMatchHighlight": "#FFA657f5",
  "editor.findMatchHighlightForeground": "#383a42f9",
  "editor.findMatchBorder": "#00000000",
  "editor.rangeHighlightBackground": "#f9ba8255",
  "editor.rangeHighlightBorder": "#00000000",
  "editor.findRangeHighlightBackground": "#f9ba8275",
  "editor.findRangeHighlightBorder": "#00000000",
  "editor.findMatchHighlightBorder": "#f0c5abf9",
  "editor.hoverHighlightBackground": "#e3ebfffa",
  "editor.wordHighlightTextBorder": "#383a4215",
  "editor.wordHighlightTextBackground": "#d0d0d0B0",
  "panelSection.border": "#383a4228",
  "peekView.border": "#4078f2",
  "peekViewEditor.background": "#f2f8fc",
  "peekViewTitle.background": "#ededed",
  "peekViewTitleLabel.foreground": "#383a42",
  "peekViewTitleDescription.foreground": "#a0a1a7",
  "peekViewResult.fileForeground": "#383a42",
  "peekViewResult.lineForeground": "#383a42",
  "peekViewResult.selectionBackground": "#e9e9e9",
  "peekViewResult.selectionForeground": "#383a42",
  "editorBracketMatch.border": "#383a4225",
  "editorRuler.foreground": "#d3d3d3",
  "gitlens.decorations.ignoredForegroundColor": "#a0a1a7",
  "git.blame.editorDecorationForeground": "#a0a1a7",
  "gitlens.trailingLineForegroundColor": "#a0a1a775",
  "notebook.cellBorderColor": "#383a4228",
  "widget.shadow": "#00000020",
  "widget.border": "#383a4228",
  "debugToolBar.border": "#383a4228",
  "extensionBadge.remoteForeground": "#ffffff",
  "editorInfo.foreground": "#4078f2",
  "chat.requestBubbleBackground": "#4078f255",
};

// Dark Default Theme Colors
export const darkDefaultColors = {
  focusBorder: "#61AFEF",
  foreground: "#CDD5DF",
  descriptionForeground: "#CDD5DF70",
  errorForeground: "#f88070",

  "textLink.foreground": "#61AFEF",
  "textLink.activeForeground": "#61AFEFE5",
  "textBlockQuote.background": "#181d25b5",
  "textBlockQuote.border": "#8B949e25",
  "textCodeBlock.background": "#181d25",
  "textPreformat.foreground": "#B8CFE650",
  "textPreformat.background": "#181d25",
  "textSeparator.foreground": "#8B949e25",

  "icon.foreground": "#CDD5DF70",
  "keybindingLabel.foreground": "#CDD5DF",
  "keybindingLabel.background": "#272f3d",
  "keybindingLabel.border": "#8B949E40",
  "keybindingLabel.bottomBorder": "#8B949e25",

  "button.background": "#61AFEF",
  "button.foreground": "#000",
  "button.hoverBackground": "#3485b6",

  "button.secondaryBackground": "#323d4d",
  "button.secondaryForeground": "#ffffffE5",
  "button.secondaryHoverBackground": "#384353",
  "button.border": "#29416100",

  "checkbox.background": "#0d1117",
  "checkbox.border": "#8B949e25",
  "checkbox.foreground": "#CDD5DF",

  "dropdown.background": "#181d25",
  "dropdown.border": "#8B949e25",
  "dropdown.foreground": "#CDD5DF",
  "dropdown.listBackground": "#181d25",

  "input.background": "#181d25",
  "input.border": "#8B949e25",
  "input.foreground": "#CDD5DF",
  "input.placeholderForeground": "#CDD5DF60",

  "badge.foreground": "#0d1117",
  "badge.background": "#61AFEF",

  "progressBar.background": "#61AFEF",

  "titleBar.activeForeground": "#CDD5DF60",
  "titleBar.activeBackground": "#0d1117",
  "titleBar.inactiveForeground": "#CDD5DF60",
  "titleBar.inactiveBackground": "#0d1117",
  "titleBar.border": "#8B949e25",

  "activityBar.foreground": "#CDD5DF",
  "activityBar.inactiveForeground": "#CDD5DF60",
  "activityBar.background": "#0d1117",
  "activityBarBadge.foreground": "#000",
  "activityBarBadge.background": "#61AFEF",
  "activityBar.activeBorder": "#FFA657",
  "activityBar.border": "#8B949e25",

  "sideBar.foreground": "#CDD5DF",
  "sideBar.background": "#0d1117",
  "sideBar.border": "#8B949e25",
  "sideBarTitle.foreground": "#CDD5DF",
  "sideBarSectionHeader.foreground": "#CDD5DF",
  "sideBarSectionHeader.background": "#00000000",
  "sideBarSectionHeader.border": "#8B949e25",

  "list.hoverForeground": "#CDD5DF",
  "list.inactiveSelectionForeground": "#CDD5DF",
  "list.activeSelectionForeground": "#CDD5DF",
  "list.hoverBackground": "#2d3139E5",
  "list.inactiveSelectionBackground": "#2d3139e5",
  "list.activeSelectionBackground": "#171b22",
  "list.inactiveFocusBackground": "#2d3139e5",
  "list.focusForeground": "#CDD5DF",
  "list.focusBackground": "#2d3139e5",
  "list.highlightForeground": "#61AFEF",

  "tree.indentGuidesStroke": "#8B949E15",

  "notificationCenterHeader.foreground": "#CDD5DF60",
  "notificationCenterHeader.background": "#30353d",
  "notifications.foreground": "#CDD5DF",
  "notifications.background": "#0d1117",
  "notifications.border": "#8B949e25",
  "notificationsErrorIcon.foreground": "#f88070",
  "notificationsWarningIcon.foreground": "#FFA657",
  "notificationsInfoIcon.foreground": "#61AFEF",

  "pickerGroup.border": "#8B949e25",
  "pickerGroup.foreground": "#61AFEF",
  "quickInput.background": "#0d1117",
  "quickInput.foreground": "#CDD5DF",

  "statusBar.foreground": "#CDD5DF60",
  "statusBar.background": "#0d1117",
  "statusBar.border": "#8B949e25",
  "statusBar.focusBorder": "#61AFEF",
  "statusBar.noFolderBackground": "#0d1117",
  "statusBar.debuggingForeground": "#FFA657",
  "statusBar.debuggingBackground": "#0d1117",
  "statusBarItem.prominentBackground": "#171b22",
  "statusBarItem.remoteForeground": "#fff",
  "statusBarItem.remoteBackground": "#212834",
  "statusBarItem.hoverBackground": "#181d25",
  "statusBarItem.activeBackground": "#1f2530",
  "statusBar.noFolderForeground": "#CDD5DF60",

  "editorGroupHeader.tabsBackground": "#0d1117",
  "editorGroupHeader.tabsBorder": "#8B949e25",
  "editorGroup.border": "#8B949e25",

  "tab.activeForeground": "#CDD5DF",
  "tab.inactiveForeground": "#CDD5DF60",
  "tab.inactiveBackground": "#0d1117",
  "tab.activeBackground": "#0d1117",
  "tab.hoverBackground": "#181d25c5",
  "tab.unfocusedHoverBackground": "#181d25c5",
  "tab.border": "#8B949e25",
  "tab.unfocusedActiveBorderTop": "#8B949e25",
  "tab.activeBorder": "#0d1117",
  "tab.unfocusedActiveBorder": "#0d1117",
  "tab.activeBorderTop": "#FFA657",

  "breadcrumb.foreground": "#CDD5DF60",
  "breadcrumb.focusForeground": "#CDD5DF",
  "breadcrumb.activeSelectionForeground": "#CDD5DF",
  "breadcrumbPicker.background": "#0d1117",

  "editor.foreground": "#CDD5DF",
  "editor.background": "#0d1117",
  "editorWidget.background": "#0d1117",
  "editor.foldBackground": "#2a2e35f9",
  "editor.lineHighlightBackground": "#171b22",
  "editor.lineHighlightBorder": "#29416100",
  "editorLineNumber.foreground": "#B8CFE650",
  "editorLineNumber.activeForeground": "#CDD5DFf5",
  "editorIndentGuide.background": "#8B949E15",
  "editorIndentGuide.activeBackground": "#8B949E25",
  "editorWhitespace.foreground": "#8B949E15",
  "editorCursor.foreground": "#FFA657",

  "editor.findMatchBackground": "#61AFEFA5",
  "editor.findMatchHighlightBackground": "#61AFEFA5",
  "editor.linkedEditingBackground": "#61AFEf25",
  "editor.inactiveSelectionBackground": "#2A4d7AA5",
  "editor.selectionBackground": "#2a4d7a",
  "editor.selectionHighlightBackground": "#61AFEf25",
  "editor.selectionHighlightBorder": "#8B949E45",
  "editor.wordHighlightBackground": "#61AFEf15",
  "editor.wordHighlightStrongBackground": "#61AFEf25",
  "editor.wordHighlightBorder": "#8B949E45",
  "editor.wordHighlightStrongBorder": "#8B949E20",
  "editorBracketMatch.background": "#61AFEf25",
  "editorBracketMatch.border": "#8B949E20",

  "editorInlayHint.background": "#181d25",
  "editorInlayHint.foreground": "#5C6A72",
  "editorInlayHint.typeBackground": "#181d25",
  "editorInlayHint.typeForeground": "#5CCFE6",
  "editorInlayHint.paramBackground": "#181d25",
  "editorInlayHint.paramForeground": "#C4B5FD",

  "editorGutter.modifiedBackground": "#79C0FF",
  "editorGutter.addedBackground": "#2EC4B6",
  "editorGutter.deletedBackground": "#F87171",

  "diffEditor.insertedLineBackground": "#2EC4B620",
  "diffEditor.insertedTextBackground": "#2EC4B635",
  "diffEditor.removedLineBackground": "#F8717120",
  "diffEditor.removedTextBackground": "#F8717135",

  "scrollbar.shadow": "#00000020",
  "scrollbarSlider.background": "#424750b5",
  "scrollbarSlider.hoverBackground": "#424750C5",
  "scrollbarSlider.activeBackground": "#424750E5",
  "editorOverviewRuler.border": "#8B949e25",

  "minimapSlider.background": "#424750b5",
  "minimapSlider.hoverBackground": "#424750C5",
  "minimapSlider.activeBackground": "#424750E5",

  "panel.background": "#0d1117",
  "panel.border": "#8B949e25",
  "panelTitle.activeBorder": "#FFA657",
  "panelTitle.activeForeground": "#CDD5DF",
  "panelTitle.inactiveForeground": "#CDD5DF60",
  "panelInput.border": "#8B949e25",

  "debugIcon.breakpointForeground": "#F87171",
  "debugConsole.infoForeground": "#79C0FF",
  "debugConsole.warningForeground": "#FBBF24",
  "debugConsole.errorForeground": "#F87171",
  "debugConsole.sourceForeground": "#E6EDF3",
  "debugConsoleInputIcon.foreground": "#79C0FF",

  "debugTokenExpression.name": "#79C0FF",
  "debugTokenExpression.value": "#E6EDF3",
  "debugTokenExpression.string": "#2EC4B6",
  "debugTokenExpression.boolean": "#F78C6C",
  "debugTokenExpression.number": "#F78C6C",
  "debugTokenExpression.error": "#F87171",

  "symbolIcon.arrayForeground": "#5CCFE6",
  "symbolIcon.booleanForeground": "#F78C6C",
  "symbolIcon.classForeground": "#5CCFE6",
  "symbolIcon.colorForeground": "#A78BFA",
  "symbolIcon.constructorForeground": "#79C0FF",
  "symbolIcon.enumeratorForeground": "#5CCFE6",
  "symbolIcon.enumeratorMemberForeground": "#F78C6C",
  "symbolIcon.eventForeground": "#FFA657",
  "symbolIcon.fieldForeground": "#FFA657",
  "symbolIcon.fileForeground": "#E6EDF3",
  "symbolIcon.folderForeground": "#FFA657",
  "symbolIcon.functionForeground": "#79C0FF",
  "symbolIcon.interfaceForeground": "#5CCFE6",
  "symbolIcon.keyForeground": "#79C0FF",
  "symbolIcon.keywordForeground": "#A78BFA",
  "symbolIcon.methodForeground": "#79C0FF",
  "symbolIcon.moduleForeground": "#5CCFE6",
  "symbolIcon.namespaceForeground": "#5CCFE6",
  "symbolIcon.nullForeground": "#5C6A72",
  "symbolIcon.numberForeground": "#F78C6C",
  "symbolIcon.objectForeground": "#5CCFE6",
  "symbolIcon.operatorForeground": "#A78BFA",
  "symbolIcon.packageForeground": "#FFA657",
  "symbolIcon.propertyForeground": "#FFA657",
  "symbolIcon.referenceForeground": "#82AAFF",
  "symbolIcon.snippetForeground": "#2EC4B6",
  "symbolIcon.stringForeground": "#2EC4B6",
  "symbolIcon.structForeground": "#5CCFE6",
  "symbolIcon.textForeground": "#E6EDF3",
  "symbolIcon.typeParameterForeground": "#C4B5FD",
  "symbolIcon.unitForeground": "#F78C6C",
  "symbolIcon.variableForeground": "#E6EDF3",
  "symbolIcon.constantForeground": "#F78C6C",

  "terminal.ansiBlack": "#0d1117",
  "terminal.ansiRed": "#F87171",
  "terminal.ansiGreen": "#2EC4B6",
  "terminal.ansiYellow": "#FBBF24",
  "terminal.ansiBlue": "#79C0FF",
  "terminal.ansiMagenta": "#A78BFA",
  "terminal.ansiCyan": "#5CCFE6",
  "terminal.ansiWhite": "#E6EDF3",
  "terminal.ansiBrightBlack": "#5C6A72",
  "terminal.ansiBrightRed": "#F47067",
  "terminal.ansiBrightGreen": "#2EC4B6",
  "terminal.ansiBrightYellow": "#FFA657",
  "terminal.ansiBrightBlue": "#82AAFF",
  "terminal.ansiBrightMagenta": "#C4B5FD",
  "terminal.ansiBrightCyan": "#5CCFE6",
  "terminal.ansiBrightWhite": "#E6EDF3",

  "editorBracketHighlight.foreground1": "#FFA657",
  "editorBracketHighlight.foreground2": "#61AFEF",
  "editorBracketHighlight.foreground3": "#F97583",
  "editorBracketHighlight.foreground4": "#B392F0",
  "editorBracketHighlight.foreground5": "#9ECBFF",
  "editorBracketHighlight.foreground6": "#CE9178",
  "editorBracketHighlight.unexpectedBracket.foreground": "#d43e4b",

  "gitDecoration.addedResourceForeground": "#2EC4B6",
  "gitDecoration.modifiedResourceForeground": "#79C0FF",
  "gitDecoration.deletedResourceForeground": "#F87171",
  "gitDecoration.untrackedResourceForeground": "#2EC4B6",
  "gitDecoration.ignoredResourceForeground": "#5C6A72",
  "gitDecoration.conflictingResourceForeground": "#FBBF24",
  "gitDecoration.submoduleResourceForeground": "#5CCFE6",

  "debugToolBar.background": "#181d25",
  "editor.stackFrameHighlightBackground": "#6e768110",
  "editor.focusedStackFrameHighlightBackground": "#2a2e35",

  "peekViewEditor.matchHighlightBackground": "#61AFEFA5",
  "peekViewResult.matchHighlightBackground": "#61AFEFA5",
  "peekViewEditor.background": "#0d1117",
  "peekViewResult.background": "#010409",

  "settings.headerForeground": "#dee4eb",
  "settings.modifiedItemIndicator": "#61AFEF",
  "welcomePage.buttonBackground": "#181d25",
  "welcomePage.buttonHoverBackground": "#2a2e35",

  "commandCenter.foreground": "#CDD5DF60",
  "commandCenter.background": "#0d1117",
  "commandCenter.border": "#8B949e25",
  "commandCenter.activeBackground": "#181d25b5",
  "commandCenter.activeForeground": "#CDD5DF60",
  "commandCenter.inactiveForeground": "#CDD5DF60",
  "commandCenter.activeBorder": "#8B949e25",
  "menubar.selectionForeground": "#CDD5DF60",
  "menubar.selectionBackground": "#181d25",
  "menubar.selectionBorder": "#00000000",
  "menu.foreground": "#CDD5DF60",
  "menu.background": "#0d1117",
  "menu.selectionForeground": "#CDD5DF",
  "menu.selectionBackground": "#2a2e35",
  "menu.selectionBorder": "#00000000",
  "menu.separatorBackground": "#8B949e25",
  "menu.border": "#8B949e25",
  "extensionIcon.privateForeground": "#CDD5DF60",
  "editorWatermark.foreground": "#CDD5DF60",
  "toolbar.hoverBackground": "#484f5b60",
  "toolbar.activeBackground": "#484f5b70",
  "extensionBadge.remoteForeground": "#B4BFCCE5",
  "extensionIcon.starForeground": "#FBBF24",
  "extensionIcon.sponsorForeground": "#A78BFA",
  "settings.settingsHeaderHoverForeground": "#E6EDF390",
  "settings.focusedRowBackground": "#6e768110",
  "editorGroup.emptyBackground": "#0d1117",
  "editorGutter.background": "#0d1117",
  "chat.requestBubbleBackground": "#181d25f9",
  "editorCodeLens.foreground": "#5C6A72",
  "editorGutter.foldingControlForeground": "#5C6A72",
  "editorOverviewRuler.background": "#0d1117",
  "editorOverviewRuler.modifiedForeground": "#79C0FF",
  "editorOverviewRuler.addedForeground": "#2EC4B6",
  "minimap.background": "#0d1117",
  "minimapGutter.addedBackground": "#2EC4B6",
  "minimapGutter.modifiedBackground": "#79C0FF",
  "editorError.foreground": "#F87171",
  "minimap.errorHighlight": "#F87171",
  "debugConsole.errorForeground": "#F87171",
  "problemsErrorIcon.foreground": "#F87171",
  "statusBarItem.errorForeground": "#F87171",
  "inputValidation.errorForeground": "#F87171",
  "editorGutter.deletedBackground": "#F87171",
  "minimapGutter.deletedBackground": "#F87171",
  "notificationsErrorIcon.foreground": "#F87171",
  "editorOverviewRuler.errorForeground": "#F87171",
  "minimap.infoHighlight": "#5C6A72",
  "editorInfo.foreground": "#79C0FF",
  "editorMarkerNavigationInfo.background": "#79C0FF20",
  "problemsInfoIcon.foreground": "#79C0FF",
  "notificationsInfoIcon.foreground": "#79C0FF",
  "debugConsole.infoForeground": "#79C0FF",
  "search.resultsInfoForeground": "#5C6A72",
  "testing.message.info.decorationForeground": "#79C0FF",
  "editorOverviewRuler.infoForeground": "#79C0FF",
  "notificationCenterHeader.background": "#30353d",
  "merge.border": "#8B949e25",
  "editorIndentGuide.background1": "#8B949E15",
  "editorIndentGuide.activeBackground1": "#8B949E25",
  "list.dropBackground": "#152438",
  "sideBar.dropBackground": "#1f2227A5",
  "editorGroup.dropBackground": "#1f2227A5",
  "widget.shadow": "#000000b5",
  "widget.border": "#8B949e25",
  "editorWidget.border": "#8B949e25",
  "editorWidget.foreground": "#CDD5DF",
  "editorWidget.background": "#0d1117",
  "editorWidget.resizeBorder": "#79C0FF",
  "pickerGroup.border": "#8B949e25",
  "notebook.cellBorderColor": "#2a2e35",
  "notebook.outputContainerBackgroundColor": "#2a2e35",
  "notebook.cellToolbarSeparator": "#2a2e35",
  "panelSection.border": "#8B949e25",
  "panelInput.border": "#8B949e25",
  "peekView.border": "#FFA657",
  "peekViewEditor.background": "#0d1117",
  "peekViewTitle.background": "#181d25",
  "peekViewResult.background": "#010409",
  "peekViewTitleDescription.foreground": "#5C6A72",
  "peekViewEditor.matchHighlightBackground": "#79C0FF45",
  "peekViewResult.matchHighlightBackground": "#79C0FF45",
  "peekViewResult.selectionBackground": "#171b22",
  "peekViewResult.selectionForeground": "#79C0FF",
  "editorBracketMatch.border": "#8B949E20",
  "editorBracketMatch.background": "#79C0FF25",
  "editorRuler.foreground": "#8B949E15",
};

// Midnight Aurora Theme Colors
export const midnightAuroraColors = {
  focusBorder: "#94bde6D5",
  foreground: "#B8CFE680",
  descriptionForeground: "#B8CFE660",
  errorForeground: "#f88070",

  "textLink.foreground": "#94BDE6",
  "textLink.activeForeground": "#acd2f8",
  "textBlockQuote.background": "#161920",
  "textBlockQuote.border": "#94bde610",
  "textCodeBlock.background": "#212531",
  "textPreformat.foreground": "#94BDE670",
  "textPreformat.background": "#161920",
  "textSeparator.foreground": "#94bde610",

  "icon.foreground": "#B8CFE680",
  "keybindingLabel.foreground": "#B8CFE680",
  "keybindingLabel.background": "#292e3e",
  "keybindingLabel.border": "#94bde620",
  "keybindingLabel.bottomBorder": "#94bde610",

  "button.background": "#94bde6",
  "button.foreground": "#000",
  "button.hoverBackground": "#acd2f8",

  "button.secondaryBackground": "#292e3e",
  "button.secondaryForeground": "#94bde6",
  "button.secondaryHoverBackground": "#384353",
  "button.border": "#94bde620",

  "checkbox.background": "#212531",
  "checkbox.border": "#94bde610",
  "checkbox.foreground": "#B8CFE6d9",

  "dropdown.background": "#212531",
  "dropdown.border": "#94bde610",
  "dropdown.foreground": "#B8CFE680",
  "dropdown.listBackground": "#161920",

  "input.background": "#212531",
  "input.border": "#94bde610",
  "input.foreground": "#B8CFE6d9",
  "input.placeholderForeground": "#B8CFE650",

  "badge.foreground": "#161920",
  "badge.background": "#94bde6",

  "progressBar.background": "#94bde6",

  "titleBar.activeForeground": "#B8CFE680",
  "titleBar.activeBackground": "#161920",
  "titleBar.inactiveForeground": "#B8CFE680",
  "titleBar.inactiveBackground": "#161920C8",
  "titleBar.border": "#94bde610",

  "activityBar.foreground": "#94BDE6B9",
  "activityBar.inactiveForeground": "#B8CFE680",
  "activityBar.background": "#161920",
  "activityBarBadge.foreground": "#161920",
  "activityBarBadge.background": "#94bde6",
  "activityBar.activeBorder": "#00000000",
  "activityBar.border": "#94bde610",

  "sideBar.foreground": "#B8CFE680",
  "sideBar.background": "#161920",
  "sideBar.border": "#94bde610",
  "sideBarTitle.foreground": "#B8CFE680",
  "sideBarSectionHeader.foreground": "#B8CFE680",
  "sideBarSectionHeader.background": "#161920",
  "sideBarSectionHeader.border": "#94bde610",

  "list.hoverForeground": "#94BDE6B5",
  "list.inactiveSelectionForeground": "#94BDE6B5",
  "list.activeSelectionForeground": "#94BDE6B5",
  "list.hoverBackground": "#292e3e",
  "list.inactiveSelectionBackground": "#292e3e",
  "list.activeSelectionBackground": "#292e3e",
  "list.inactiveFocusBackground": "#292e3e",
  "list.focusForeground": "#94BDE6B5",
  "list.focusBackground": "#292e3e",
  "list.highlightForeground": "#94BDE6",

  "tree.indentGuidesStroke": "#94BDE635",

  "notificationCenterHeader.foreground": "#B8CFE680",
  "notificationCenterHeader.background": "#161920",
  "notifications.foreground": "#B8CFE680",
  "notifications.background": "#161920",
  "notifications.border": "#94bde610",
  "notificationsErrorIcon.foreground": "#f88070",
  "notificationsWarningIcon.foreground": "#D19A66d5",
  "notificationsInfoIcon.foreground": "#94bde6",

  "pickerGroup.border": "#94bde610",
  "pickerGroup.foreground": "#94bde6",
  "quickInput.background": "#161920",
  "quickInput.foreground": "#B8CFE6d9",

  "statusBar.foreground": "#B8CFE680",
  "statusBar.background": "#161920",
  "statusBar.border": "#94bde615",
  "statusBar.focusBorder": "#94bde6D5",
  "statusBar.noFolderBackground": "#161920",
  "statusBar.debuggingForeground": "#61AFEF",
  "statusBar.debuggingBackground": "#161920",
  "statusBarItem.prominentBackground": "#292e3e",
  "statusBarItem.remoteForeground": "#B4BFCCE5",
  "statusBarItem.remoteBackground": "#292e3e",
  "statusBarItem.hoverBackground": "#292e3e",
  "statusBarItem.activeBackground": "#31374bc5",
  "statusBar.noFolderForeground": "#B4BFCC",

  "editorGroupHeader.tabsBackground": "#161920",
  "editorGroupHeader.tabsBorder": "#94bde610",
  "editorGroup.border": "#94bde610",

  "tab.activeForeground": "#94BDE6B5",
  "tab.inactiveForeground": "#B8CFE680",
  "tab.inactiveBackground": "#161920",
  "tab.activeBackground": "#161920",
  "tab.hoverBackground": "#161920",
  "tab.unfocusedHoverBackground": "#161920",
  "tab.border": "#94bde610",
  "tab.unfocusedActiveBorderTop": "#94bde610",
  "tab.activeBorder": "#161920",
  "tab.unfocusedActiveBorder": "#161920",
  "tab.activeBorderTop": "#94BDE6B5",

  "breadcrumb.foreground": "#B8CFE680",
  "breadcrumb.focusForeground": "#94BDE6B5",
  "breadcrumb.activeSelectionForeground": "#94BDE6B5",
  "breadcrumbPicker.background": "#161920",

  "editor.foreground": "#B8CFE6D5",
  "editor.background": "#161920",
  "editorWidget.background": "#161920",
  "editor.foldBackground": "#292e3ef9",
  "editor.lineHighlightBackground": "#292e3e",
  "editor.lineHighlightBorder": "#8B949E05",
  "editorLineNumber.foreground": "#94BDE670",
  "editorLineNumber.activeForeground": "#B8CFE6C5",
  "editorIndentGuide.background": "#94BDE615",
  "editorIndentGuide.activeBackground": "#94BDE645",
  "editorWhitespace.foreground": "#8B949E95",
  "editorCursor.foreground": "#FFA657",

  "editor.findMatchBackground": "#94bde644",
  "editor.findMatchHighlightBackground": "#94bde655",
  "editor.linkedEditingBackground": "#94bde644",
  "editor.inactiveSelectionBackground": "#9ECBFF50",
  "editor.selectionBackground": "#9ECBFF50",
  "editor.selectionHighlightBackground": "#94bde628",
  "editor.selectionHighlightBorder": "#8B949E20",
  "editor.wordHighlightBackground": "#94bde625",
  "editor.wordHighlightStrongBackground": "#94bde625",
  "editor.wordHighlightBorder": "#8B949E20",
  "editor.wordHighlightStrongBorder": "#8B949E20",
  "editorBracketMatch.background": "#8B949E25",
  "editorBracketMatch.border": "#8B949E20",

  "editorInlayHint.background": "#161920",
  "editorInlayHint.foreground": "#94BDE670",
  "editorInlayHint.typeBackground": "#161920",
  "editorInlayHint.typeForeground": "#94BDE670",
  "editorInlayHint.paramBackground": "#161920",
  "editorInlayHint.paramForeground": "#94BDE670",

  "editorGutter.modifiedBackground": "#61AFEF",
  "editorGutter.addedBackground": "#8DDB8Cd5",
  "editorGutter.deletedBackground": "#f88070",

  "diffEditor.insertedLineBackground": "#8DDB8C10",
  "diffEditor.insertedTextBackground": "#8DDB8C10",
  "diffEditor.removedLineBackground": "#f8807010",
  "diffEditor.removedTextBackground": "#f8807010",

  "scrollbar.shadow": "#00000040",
  "scrollbarSlider.background": "#94BDE650",
  "scrollbarSlider.hoverBackground": "#94BDE660",
  "scrollbarSlider.activeBackground": "#94BDE675",
  "editorOverviewRuler.border": "#8B949E25",

  "minimapSlider.background": "#94BDE650",
  "minimapSlider.hoverBackground": "#94BDE660",
  "minimapSlider.activeBackground": "#94BDE675",

  "panel.background": "#161920",
  "panel.border": "#94bde610",
  "panelTitle.activeBorder": "#94BDE6a5",
  "panelTitle.activeForeground": "#94BDE6B5",
  "panelTitle.inactiveForeground": "#94BDE655",
  "panelInput.border": "#8B949e25",

  "debugIcon.breakpointForeground": "#f88070",
  "debugConsole.infoForeground": "#61AFEF",
  "debugConsole.warningForeground": "#D19A66d5",
  "debugConsole.errorForeground": "#f88070",
  "debugConsole.sourceForeground": "#B8CFE6D5",
  "debugConsoleInputIcon.foreground": "#94bde6",

  "debugTokenExpression.name": "#94bde6",
  "debugTokenExpression.value": "#B8CFE6D5",
  "debugTokenExpression.string": "#CE9178",
  "debugTokenExpression.boolean": "#8DDB8Cd5",
  "debugTokenExpression.number": "#F97583",
  "debugTokenExpression.error": "#f88070",

  "symbolIcon.arrayForeground": "#9ECBFF",
  "symbolIcon.booleanForeground": "#8DDB8Cd5",
  "symbolIcon.classForeground": "#B392F0",
  "symbolIcon.colorForeground": "#94bde6",
  "symbolIcon.constructorForeground": "#94bde6",
  "symbolIcon.enumeratorForeground": "#9ECBFF",
  "symbolIcon.enumeratorMemberForeground": "#9ECBFF",
  "symbolIcon.eventForeground": "#94BDE670",
  "symbolIcon.fieldForeground": "#94BDE670",
  "symbolIcon.fileForeground": "#B8CFE680",
  "symbolIcon.folderForeground": "#B8CFE680",
  "symbolIcon.functionForeground": "#94bde6",
  "symbolIcon.interfaceForeground": "#B392F0",
  "symbolIcon.keyForeground": "#94bde6",
  "symbolIcon.keywordForeground": "#B392F0",
  "symbolIcon.methodForeground": "#94bde6",
  "symbolIcon.moduleForeground": "#B392F0",
  "symbolIcon.namespaceForeground": "#B392F0",
  "symbolIcon.nullForeground": "#94BDE670",
  "symbolIcon.numberForeground": "#F97583",
  "symbolIcon.objectForeground": "#B392F0",
  "symbolIcon.operatorForeground": "#94bde6",
  "symbolIcon.packageForeground": "#B392F0",
  "symbolIcon.propertyForeground": "#B392F0",
  "symbolIcon.referenceForeground": "#94bde6",
  "symbolIcon.snippetForeground": "#94bde6",
  "symbolIcon.stringForeground": "#CE9178",
  "symbolIcon.structForeground": "#B392F0",
  "symbolIcon.textForeground": "#B8CFE6D5",
  "symbolIcon.typeParameterForeground": "#B392F0",
  "symbolIcon.unitForeground": "#94bde6",
  "symbolIcon.variableForeground": "#B8CFE6D5",
  "symbolIcon.constantForeground": "#F97583",

  "terminal.ansiBlack": "#121212",
  "terminal.ansiRed": "#d43e4b",
  "terminal.ansiGreen": "#8DDB8Cd5",
  "terminal.ansiYellow": "#CE9178",
  "terminal.ansiBlue": "#2E95D3",
  "terminal.ansiMagenta": "#B392F0",
  "terminal.ansiCyan": "#7ea2cc",
  "terminal.ansiWhite": "#B8CFE6C5",
  "terminal.ansiBrightBlack": "#B8CFE670",
  "terminal.ansiBrightRed": "#fc6776",
  "terminal.ansiBrightGreen": "#8DDB8Cd5",
  "terminal.ansiBrightYellow": "#FFA657",
  "terminal.ansiBrightBlue": "#61AFEF",
  "terminal.ansiBrightMagenta": "#C678DD",
  "terminal.ansiBrightCyan": "#9ECBFF",
  "terminal.ansiBrightWhite": "#c7daec",

  "editorBracketHighlight.foreground1": "#FFA657",
  "editorBracketHighlight.foreground2": "#61AFEF",
  "editorBracketHighlight.foreground3": "#F97583",
  "editorBracketHighlight.foreground4": "#B392F0",
  "editorBracketHighlight.foreground5": "#9ECBFF",
  "editorBracketHighlight.foreground6": "#CE9178",
  "editorBracketHighlight.unexpectedBracket.foreground": "#f88070",

  "gitDecoration.addedResourceForeground": "#8DDB8Cd5",
  "gitDecoration.modifiedResourceForeground": "#61AFEF",
  "gitDecoration.deletedResourceForeground": "#f88070",
  "gitDecoration.untrackedResourceForeground": "#8DDB8Cd5",
  "gitDecoration.ignoredResourceForeground": "#ABBAC742",
  "gitDecoration.conflictingResourceForeground": "#B392F0",
  "gitDecoration.submoduleResourceForeground": "#61AFEF",

  "debugToolBar.background": "#161920",
  "editor.stackFrameHighlightBackground": "#424a6470",
  "editor.focusedStackFrameHighlightBackground": "#292e3e",

  "peekViewEditor.matchHighlightBackground": "#94bde644",
  "peekViewResult.matchHighlightBackground": "#94bde655",
  "peekViewEditor.background": "#161920",
  "peekViewResult.background": "#202430",

  "settings.headerForeground": "#94BDE6B5",
  "settings.modifiedItemIndicator": "#94BDE6B5",
  "welcomePage.buttonBackground": "#292e3e",
  "welcomePage.buttonHoverBackground": "#424a64",

  "commandCenter.foreground": "#B8CFE680",
  "commandCenter.background": "#161920",
  "commandCenter.border": "#94bde610",
  "commandCenter.activeBackground": "#1a1d27c5",
  "commandCenter.activeForeground": "#B8CFE680",
  "commandCenter.inactiveForeground": "#B8CFE680",
  "commandCenter.activeBorder": "#94bde610",
  "menubar.selectionForeground": "#94BDE6B5",
  "menubar.selectionBackground": "#424a6470",
  "menubar.selectionBorder": "#00000000",
  "menu.foreground": "#B8CFE680",
  "menu.background": "#161920",
  "menu.selectionForeground": "#94BDE6B5",
  "menu.selectionBackground": "#292e3e",
  "menu.selectionBorder": "#00000000",
  "menu.separatorBackground": "#94bde610",
  "menu.border": "#94bde610",
  "extensionIcon.starForeground": "#f97583",
  "extensionIcon.sponsorForeground": "#b392f0",
  "editorGroup.emptyBackground": "#161920",
  "editorGutter.background": "#161920",
  "chat.requestBubbleBackground": "#1a1d27c5",
  "editorCodeLens.foreground": "#94BDE670",
  "editorGutter.foldingControlForeground": "#94BDE670",
  "editorOverviewRuler.background": "#161920",
  "editorOverviewRuler.modifiedForeground": "#61AFEF",
  "editorOverviewRuler.addedForeground": "#8DDB8Cd5",
  "minimap.background": "#161920",
  "minimapGutter.addedBackground": "#8DDB8Cd5",
  "minimapGutter.modifiedBackground": "#61AFEF",
  "editorError.foreground": "#f14c4c",
  "minimap.errorHighlight": "#f14c4c",
  "debugConsole.errorForeground": "#f88070",
  "problemsErrorIcon.foreground": "#f88070",
  "statusBarItem.errorForeground": "#f88070",
  "inputValidation.errorForeground": "#f88070",
  "editorGutter.deletedBackground": "#f88070",
  "minimapGutter.deletedBackground": "#f88070",
  "notificationsErrorIcon.foreground": "#f88070",
  "editorOverviewRuler.errorForeground": "#f88070",
  "minimap.infoHighlight": "#94BDE670",
  "editorInfo.foreground": "#94BDE670",
  "editorMarkerNavigationInfo.background": "#94BDE670",
  "problemsInfoIcon.foreground": "#61AFEF",
  "notificationsInfoIcon.foreground": "#61AFEF",
  "debugConsole.infoForeground": "#61AFEF",
  "search.resultsInfoForeground": "#94BDE670",
  "testing.message.info.decorationForeground": "#94BDE670",
  "editorOverviewRuler.infoForeground": "#94BDE670",
  "merge.border": "#8B949E25",
  "editorIndentGuide.background1": "#94BDE615",
  "editorIndentGuide.activeBackground1": "#94BDE645",
  "list.dropBackground": "#212530",
  "sideBar.dropBackground": "#212530B5",
  "editorGroup.dropBackground": "#212530B5",
  "widget.shadow": "#00000040",
  "widget.border": "#8B949E25",
  "editorWidget.border": "#8B949E25",
  "editorWidget.foreground": "#B8CFE680",
  "editorWidget.background": "#161920",
  "editorWidget.resizeBorder": "#94bde6B5",
  "pickerGroup.border": "#94bde610",
  "notebook.cellBorderColor": "#8B949E25",
  "notebook.outputContainerBackgroundColor": "#292e3e99",
  "notebook.outputContainerBorderColor": "#292e3e99",
  "panelSection.border": "#8B949e25",
  "panelInput.border": "#8B949e25",
  "peekView.border": "#94bde6",
  "peekViewEditor.background": "#161920",
  "peekViewTitle.background": "#292e3e",
  "peekViewResult.background": "#202430",
  "peekViewTitleLabel.foreground": "#94BDE6B5",
  "peekViewTitleDescription.foreground": "#94BDE655",
  "peekViewEditor.matchHighlightBackground": "#94bde644",
  "peekViewResult.matchHighlightBackground": "#94bde655",
  "peekViewResult.selectionBackground": "#424a64",
  "peekViewResult.selectionForeground": "#94BDE6B5",
  "editorBracketMatch.border": "#8B949E20",
  "editorRuler.foreground": "#ffffff1a",
};

// Stellar Nova Theme Colors
export const stellarNovaColors = {
  focusBorder: "#61AFEF",
  foreground: "#ADBAC7",
  descriptionForeground: "#ADBAC790",
  errorForeground: "#f88070",

  "textLink.foreground": "#61AFEF",
  "textLink.activeForeground": "#61AFEFE5",
  "textBlockQuote.background": "#2c323a90",
  "textBlockQuote.border": "#8B949e25",
  "textCodeBlock.background": "#2c323a",
  "textPreformat.foreground": "#ADBAC760",
  "textPreformat.background": "#2c323a",
  "textSeparator.foreground": "#8B949e25",

  "icon.foreground": "#ADBAC790",
  "keybindingLabel.foreground": "#ADBAC7",
  "keybindingLabel.background": "#2d333b",
  "keybindingLabel.border": "#8B949E40",
  "keybindingLabel.bottomBorder": "#8B949e25",

  "button.background": "#61AFEF",
  "button.foreground": "#000",
  "button.hoverBackground": "#3485b6",

  "button.secondaryBackground": "#616d7aD5",
  "button.secondaryForeground": "#ffffffe5",
  "button.secondaryHoverBackground": "#616d7aA5",
  "button.border": "#29416100",

  "checkbox.background": "#2d333b",
  "checkbox.border": "#8B949e25",
  "checkbox.foreground": "#ADBAC7",

  "dropdown.background": "#2c323a",
  "dropdown.border": "#8B949e25",
  "dropdown.foreground": "#ADBAC7",
  "dropdown.listBackground": "#2d333b",

  "input.background": "#2c323a",
  "input.border": "#8B949e25",
  "input.foreground": "#ADBAC7",
  "input.placeholderForeground": "#ABBAC780",

  "badge.foreground": "#fff",
  "badge.background": "#61AFEF",

  "progressBar.background": "#61AFEF",

  "titleBar.activeForeground": "#ADBAC790",
  "titleBar.activeBackground": "#22272e",
  "titleBar.inactiveForeground": "#ADBAC790",
  "titleBar.inactiveBackground": "#22272e",
  "titleBar.border": "#8B949e25",

  "activityBar.foreground": "#ADBAC7",
  "activityBar.inactiveForeground": "#ADBAC790",
  "activityBar.background": "#22272e",
  "activityBarBadge.foreground": "#000",
  "activityBarBadge.background": "#61AFEF",
  "activityBar.activeBorder": "#FFA657",
  "activityBar.border": "#8B949e25",

  "sideBar.foreground": "#ADBAC7",
  "sideBar.background": "#22272e",
  "sideBar.border": "#8B949e25",
  "sideBarTitle.foreground": "#ADBAC7",
  "sideBarSectionHeader.foreground": "#ADBAC7",
  "sideBarSectionHeader.background": "#00000000",
  "sideBarSectionHeader.border": "#8B949e25",

  "list.hoverForeground": "#ADBAC7",
  "list.inactiveSelectionForeground": "#ADBAC7",
  "list.activeSelectionForeground": "#ADBAC7",
  "list.hoverBackground": "#434b54",
  "list.inactiveSelectionBackground": "#434b54",
  "list.activeSelectionBackground": "#434b54",
  "list.inactiveFocusBackground": "#434b54",
  "list.focusForeground": "#ADBAC7",
  "list.focusBackground": "#434b54",
  "list.highlightForeground": "#61AFEF",

  "tree.indentGuidesStroke": "#8B949E30",

  "notificationCenterHeader.foreground": "#ADBAC790",
  "notificationCenterHeader.background": "#2d333b",
  "notifications.foreground": "#ADBAC7",
  "notifications.background": "#22272e",
  "notifications.border": "#8B949e25",
  "notificationsErrorIcon.foreground": "#f88070",
  "notificationsWarningIcon.foreground": "#FFA657",
  "notificationsInfoIcon.foreground": "#61AFEF",

  "pickerGroup.border": "#8B949e25",
  "pickerGroup.foreground": "#61AFEF",
  "quickInput.background": "#2d333b",
  "quickInput.foreground": "#ADBAC7",

  "statusBar.foreground": "#ADBAC790",
  "statusBar.background": "#22272e",
  "statusBar.border": "#8B949e25",
  "statusBar.focusBorder": "#61AFEF",
  "statusBar.noFolderBackground": "#22272e",
  "statusBar.debuggingForeground": "#FFA657",
  "statusBar.debuggingBackground": "#22272e",
  "statusBarItem.prominentBackground": "#434b54",
  "statusBarItem.remoteForeground": "#fff",
  "statusBarItem.remoteBackground": "#2d333b",
  "statusBarItem.hoverBackground": "#2f3439",
  "statusBarItem.activeBackground": "#2f3439C5",
  "statusBar.noFolderForeground": "#ADBAC7",

  "editorGroupHeader.tabsBackground": "#22272e",
  "editorGroupHeader.tabsBorder": "#8B949e25",
  "editorGroup.border": "#8B949e25",

  "tab.activeForeground": "#ADBAC7",
  "tab.inactiveForeground": "#ADBAC790",
  "tab.inactiveBackground": "#22272e",
  "tab.activeBackground": "#22272e",
  "tab.hoverBackground": "#242a31",
  "tab.unfocusedHoverBackground": "#242a31",
  "tab.border": "#8B949e25",
  "tab.unfocusedActiveBorderTop": "#8B949e25",
  "tab.activeBorder": "#22272e",
  "tab.unfocusedActiveBorder": "#22272e",
  "tab.activeBorderTop": "#FFA657",

  "breadcrumb.foreground": "#ADBAC790",
  "breadcrumb.focusForeground": "#ADBAC7",
  "breadcrumb.activeSelectionForeground": "#ADBAC7",
  "breadcrumbPicker.background": "#2d333b",

  "editor.foreground": "#ADBAC7",
  "editor.background": "#22272e",
  "editorWidget.background": "#2d333b",
  "editor.foldBackground": "#2c323af9",
  "editor.lineHighlightBackground": "#2c323a",
  "editor.lineHighlightBorder": "#29416100",
  "editorLineNumber.foreground": "#ADBAC760",
  "editorLineNumber.activeForeground": "#ADBAC7",
  "editorIndentGuide.background": "#8B949E15",
  "editorIndentGuide.activeBackground": "#8B949E30",
  "editorWhitespace.foreground": "#8B949E30",
  "editorCursor.foreground": "#FFA657",

  "editor.findMatchBackground": "#61AFEFE5",
  "editor.findMatchHighlightBackground": "#61AFEFA5",
  "editor.linkedEditingBackground": "#61AFEf25",
  "editor.inactiveSelectionBackground": "#2A4d7AA5",
  "editor.selectionBackground": "#2a4d7a",
  "editor.selectionHighlightBackground": "#61AFEf25",
  "editor.selectionHighlightBorder": "#8B949E40",
  "editor.wordHighlightBackground": "#61AFEf15",
  "editor.wordHighlightStrongBackground": "#61AFEf20",
  "editor.wordHighlightBorder": "#8B949E40",
  "editor.wordHighlightStrongBorder": "#8B949E20",
  "editorBracketMatch.background": "#29416155",
  "editorBracketMatch.border": "#8B949E45",

  "editorInlayHint.background": "#2c323a",
  "editorInlayHint.foreground": "#768390",
  "editorInlayHint.typeBackground": "#2c323a",
  "editorInlayHint.typeForeground": "#768390",
  "editorInlayHint.paramBackground": "#2c323a",
  "editorInlayHint.paramForeground": "#768390",

  "editorGutter.modifiedBackground": "#61AFEF",
  "editorGutter.addedBackground": "#8DDB8Cd5",
  "editorGutter.deletedBackground": "#f88070",

  "diffEditor.insertedLineBackground": "#8DDB8C10",
  "diffEditor.insertedTextBackground": "#8DDB8C10",
  "diffEditor.removedLineBackground": "#f8807010",
  "diffEditor.removedTextBackground": "#f8807010",

  "scrollbar.shadow": "#00000020",
  "scrollbarSlider.background": "#434b54b5",
  "scrollbarSlider.hoverBackground": "#434b54C5",
  "scrollbarSlider.activeBackground": "#434b54E5",
  "editorOverviewRuler.border": "#8B949e25",

  "minimapSlider.background": "#434b54b5",
  "minimapSlider.hoverBackground": "#434b54C5",
  "minimapSlider.activeBackground": "#434b54E5",

  "panel.background": "#22272e",
  "panel.border": "#8B949e25",
  "panelTitle.activeBorder": "#FFA657",
  "panelTitle.activeForeground": "#ADBAC7",
  "panelTitle.inactiveForeground": "#ABBAC780",
  "panelInput.border": "#8B949e25",

  "debugIcon.breakpointForeground": "#f88070",
  "debugConsole.infoForeground": "#61AFEF",
  "debugConsole.warningForeground": "#FFA657",
  "debugConsole.errorForeground": "#f88070",
  "debugConsole.sourceForeground": "#ADBAC7",
  "debugConsoleInputIcon.foreground": "#61AFEF",

  "debugTokenExpression.name": "#61AFEF",
  "debugTokenExpression.value": "#ADBAC7",
  "debugTokenExpression.string": "#CE9178",
  "debugTokenExpression.boolean": "#8DDB8Cd5",
  "debugTokenExpression.number": "#F97583",
  "debugTokenExpression.error": "#f88070",

  "symbolIcon.arrayForeground": "#9ECBFF",
  "symbolIcon.booleanForeground": "#8DDB8Cd5",
  "symbolIcon.classForeground": "#B392F0",
  "symbolIcon.colorForeground": "#61AFEF",
  "symbolIcon.constructorForeground": "#61AFEF",
  "symbolIcon.enumeratorForeground": "#9ECBFF",
  "symbolIcon.enumeratorMemberForeground": "#9ECBFF",
  "symbolIcon.eventForeground": "#768390",
  "symbolIcon.fieldForeground": "#768390",
  "symbolIcon.fileForeground": "#ADBAC7",
  "symbolIcon.folderForeground": "#ADBAC7",
  "symbolIcon.functionForeground": "#61AFEF",
  "symbolIcon.interfaceForeground": "#B392F0",
  "symbolIcon.keyForeground": "#61AFEF",
  "symbolIcon.keywordForeground": "#B392F0",
  "symbolIcon.methodForeground": "#61AFEF",
  "symbolIcon.moduleForeground": "#B392F0",
  "symbolIcon.namespaceForeground": "#B392F0",
  "symbolIcon.nullForeground": "#768390",
  "symbolIcon.numberForeground": "#F97583",
  "symbolIcon.objectForeground": "#B392F0",
  "symbolIcon.operatorForeground": "#61AFEF",
  "symbolIcon.packageForeground": "#B392F0",
  "symbolIcon.propertyForeground": "#B392F0",
  "symbolIcon.referenceForeground": "#61AFEF",
  "symbolIcon.snippetForeground": "#61AFEF",
  "symbolIcon.stringForeground": "#CE9178",
  "symbolIcon.structForeground": "#B392F0",
  "symbolIcon.textForeground": "#ADBAC7",
  "symbolIcon.typeParameterForeground": "#B392F0",
  "symbolIcon.unitForeground": "#61AFEF",
  "symbolIcon.variableForeground": "#ADBAC7",
  "symbolIcon.constantForeground": "#F97583",

  "terminal.ansiBlack": "#121212",
  "terminal.ansiRed": "#d43e4b",
  "terminal.ansiGreen": "#8DDB8Cd5",
  "terminal.ansiYellow": "#CE9178",
  "terminal.ansiBlue": "#2E95D3",
  "terminal.ansiMagenta": "#B392F0",
  "terminal.ansiCyan": "#7ea2cc",
  "terminal.ansiWhite": "#ADBAC7",
  "terminal.ansiBrightBlack": "#ADBAC780",
  "terminal.ansiBrightRed": "#fc6776",
  "terminal.ansiBrightGreen": "#4BCF94D5",
  "terminal.ansiBrightYellow": "#FFA657",
  "terminal.ansiBrightBlue": "#61AFEF",
  "terminal.ansiBrightMagenta": "#C678DD",
  "terminal.ansiBrightCyan": "#9ECBFF",
  "terminal.ansiBrightWhite": "#eeeff0",

  "editorBracketHighlight.foreground1": "#FFA657",
  "editorBracketHighlight.foreground2": "#61AFEF",
  "editorBracketHighlight.foreground3": "#F97583",
  "editorBracketHighlight.foreground4": "#B392F0",
  "editorBracketHighlight.foreground5": "#9ECBFF",
  "editorBracketHighlight.foreground6": "#CE9178",
  "editorBracketHighlight.unexpectedBracket.foreground": "#d43e4b",

  "gitDecoration.addedResourceForeground": "#8DDB8Cd5",
  "gitDecoration.modifiedResourceForeground": "#61AFEF",
  "gitDecoration.deletedResourceForeground": "#f88070",
  "gitDecoration.untrackedResourceForeground": "#8DDB8Cd5",
  "gitDecoration.ignoredResourceForeground": "#ABBAC770",
  "gitDecoration.conflictingResourceForeground": "#B392F0",
  "gitDecoration.submoduleResourceForeground": "#61AFEF",

  "debugToolBar.background": "#22272e",
  "editor.stackFrameHighlightBackground": "#616d7a60",
  "editor.focusedStackFrameHighlightBackground": "#434b54",

  "peekViewEditor.matchHighlightBackground": "#61AFEFA5",
  "peekViewResult.matchHighlightBackground": "#61AFEFA5",
  "peekViewEditor.background": "#22272e",
  "peekViewResult.background": "#2d333b",

  "settings.headerForeground": "#ADBAC7",
  "settings.modifiedItemIndicator": "#61AFEF",
  "welcomePage.buttonBackground": "#2c323a",
  "welcomePage.buttonHoverBackground": "#434b54",

  "commandCenter.foreground": "#ADBAC790",
  "commandCenter.background": "#2c323a90",
  "commandCenter.border": "#8B949e25",
  "commandCenter.activeBackground": "#2c323a",
  "commandCenter.activeForeground": "#ADBAC7B5",
  "commandCenter.inactiveForeground": "#ADBAC790",
  "commandCenter.activeBorder": "#8B949e25",
  "menubar.selectionForeground": "#ADBAC7B5",
  "menubar.selectionBackground": "#616d7a60",
  "menubar.selectionBorder": "#00000000",
  "menu.foreground": "#ADBAC7",
  "menu.background": "#2d333b",
  "menu.selectionForeground": "#ADBAC7",
  "menu.selectionBackground": "#434b54",
  "menu.selectionBorder": "#00000000",
  "menu.separatorBackground": "#8B949e25",
  "menu.border": "#8B949e25",
  "extensionIcon.starForeground": "#f97583",
  "extensionIcon.sponsorForeground": "#b392f0",
  "editorGroup.emptyBackground": "#22272e",
  "editorGutter.background": "#22272e",
  "chat.requestBubbleBackground": "#2c323af9",
  "editorCodeLens.foreground": "#768390",
  "editorGutter.foldingControlForeground": "#ADBAC790",
  "editorOverviewRuler.background": "#22272e",
  "editorOverviewRuler.modifiedForeground": "#61AFEF",
  "editorOverviewRuler.addedForeground": "#8DDB8Cd5",
  "minimap.background": "#22272e",
  "minimapGutter.addedBackground": "#8DDB8Cd5",
  "minimapGutter.modifiedBackground": "#61AFEF",
  "editorError.foreground": "#f14c4c",
  "minimap.errorHighlight": "#f14c4c",
  "debugConsole.errorForeground": "#f88070",
  "problemsErrorIcon.foreground": "#f88070",
  "statusBarItem.errorForeground": "#f88070",
  "inputValidation.errorForeground": "#f88070",
  "editorGutter.deletedBackground": "#f88070",
  "minimapGutter.deletedBackground": "#f88070",
  "notificationsErrorIcon.foreground": "#f88070",
  "editorOverviewRuler.errorForeground": "#f14c4c",
  "minimap.infoHighlight": "#768390",
  "editorInfo.foreground": "#768390",
  "editorMarkerNavigationInfo.background": "#768390",
  "problemsInfoIcon.foreground": "#61AFEF",
  "notificationsInfoIcon.foreground": "#61AFEF",
  "debugConsole.infoForeground": "#61AFEF",
  "search.resultsInfoForeground": "#768390",
  "testing.message.info.decorationForeground": "#768390",
  "editorOverviewRuler.infoForeground": "#768390",
  "merge.border": "#8B949e25",
  "editorIndentGuide.background1": "#8B949E15",
  "editorIndentGuide.activeBackground1": "#8B949E30",
  "list.dropBackground": "#1c2d44",
  "sideBar.dropBackground": "#434b5480",
  "editorGroup.dropBackground": "#434b5480",
  "widget.shadow": "#00000045",
  "widget.border": "#8B949e25",
  "editorWidget.border": "#8B949e25",
  "editorWidget.foreground": "#ADBAC7",
  "editorWidget.background": "#2d333b",
  "editorWidget.resizeBorder": "#61AFEF",
  "pickerGroup.border": "#8B949e25",
  "notebook.cellBorderColor": "#394049",
  "notebook.cellEditorBackground": "#1c2128",
  "notebook.selectedCellBackground": "#394049",
  "notebook.cellToolbarSeparator": "#394049",
  "panelSection.border": "#8B949e25",
  "panelInput.border": "#8B949e25",
  "peekView.border": "#FFA657",
  "peekViewEditor.background": "#22272e",
  "peekViewTitle.background": "#1f242b",
  "peekViewResult.background": "#2d333b",
  "peekViewTitleLabel.foreground": "#ABBAC7",
  "peekViewTitleDescription.foreground": "#ABBAC780",
  "peekViewEditor.matchHighlightBackground": "#61AFEFA5",
  "peekViewResult.matchHighlightBackground": "#61AFEFA5",
  "peekViewResult.selectionBackground": "#434b54",
  "peekViewResult.selectionForeground": "#61AFEF",
  "editorBracketMatch.border": "#8B949E45",
  "editorRuler.foreground": "#8B949E30",
};
