name: Release

on:
  push:
    paths:
      - '.github/release-info.md'
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug File Content
        run: |
          echo "Checking release-info.md content:"
          cat .github/release-info.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.3
          release_name: BedarX Pro v0.0.3
          body_path: .github/release-info.md
          draft: false
          prerelease: false